name: Wonder Master Build
on: 
  push:
    branches:
      - master
    tags-ignore:
      - wonder-*
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Wonder Source Code
      uses: actions/checkout@v1

    - name: Cache Maven Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2 # maven dependencies are stored in `~/.m2` on Linux
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Deploy Snapshots with Maven
      run: mvn -B deploy --file pom.xml -s .maven_settings.xml -DretryFailedDeploymentCount=10
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
